### ISSUE TITLE
BlackOps Adv Command Units Aeon upgrade broken

### ISSUE THREAD

**Issue by TheSniperFan** [Tanksy/Git-LOUD#4]
**Mod:** BlackOps Advanced Command Units for LOUD
**Faction:** Aeon
**Upgrade:** "Dual Miasma Artillery" (Right Arm)
**Problem:** The upgrade doesn't do anything whatsoever. Neither hostile structures nor units are targeted. The lua log doesn't print any warnings/errors either (aside from the usual background noise about some missing icons for BlackOps).

**Comment by Sprouto** [comment]
We corrected this issue - finally.
