### ISSUE TITLE
Place to submit bug reports / feature requests?

### ISSUE THREAD

**Issue by bctrainers** [Tanksy/Git-LOUD#8]
Quick question, is there a suitable location for bug reports and feature requests? I am unsure if Github would be an ideal place to post such.

**Comment by Sprouto** [comment]
Sorry for the long delay - I only just saw this today.
Our Discord (link can be found in the HELP tab of the launcher) is the primary place to report issues and talk about feature requests and such.   We're happy to engage in any conversation that revolves around the project.
